
package sm.ciscoop.clientws2;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.1-b01-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IImportaMalattie", targetNamespace = "http://importa.ciscoop.sm/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IImportaMalattie {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "importaMalattie", targetNamespace = "http://importa.ciscoop.sm/", className = "sm.ciscoop.clientws2.ImportaMalattie")
    @ResponseWrapper(localName = "importaMalattieResponse", targetNamespace = "http://importa.ciscoop.sm/", className = "sm.ciscoop.clientws2.ImportaMalattieResponse")
    @Action(input = "http://importa.ciscoop.sm/IImportaMalattie/importaMalattieRequest", output = "http://importa.ciscoop.sm/IImportaMalattie/importaMalattieResponse")
    public String importaMalattie(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<sm.ciscoop.clientws2.Malattia>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "importazione", targetNamespace = "http://importa.ciscoop.sm/", className = "sm.ciscoop.clientws2.Importazione")
    @ResponseWrapper(localName = "importazioneResponse", targetNamespace = "http://importa.ciscoop.sm/", className = "sm.ciscoop.clientws2.ImportazioneResponse")
    @Action(input = "http://importa.ciscoop.sm/IImportaMalattie/importazioneRequest", output = "http://importa.ciscoop.sm/IImportaMalattie/importazioneResponse")
    public List<Malattia> importazione(
        @WebParam(name = "arg0", targetNamespace = "")
        Malattia arg0);

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isOnline", targetNamespace = "http://importa.ciscoop.sm/", className = "sm.ciscoop.clientws2.IsOnline")
    @ResponseWrapper(localName = "isOnlineResponse", targetNamespace = "http://importa.ciscoop.sm/", className = "sm.ciscoop.clientws2.IsOnlineResponse")
    @Action(input = "http://importa.ciscoop.sm/IImportaMalattie/isOnlineRequest", output = "http://importa.ciscoop.sm/IImportaMalattie/isOnlineResponse")
    public boolean isOnline();

}
